all:
	sbatch md1000.job
	sbatch md1331.job
	sbatch md1728.job
	sbatch md2197.job
	sbatch md2744.job
	sbatch md3375.job
	sbatch md4096.job
	sbatch md4913.job
	sbatch md5832.job
	sbatch md6859.job
	sbatch md8000.job
	